"""empty message

Revision ID: 36f0260a1cdf
Revises: 39b38487f235
Create Date: 2022-08-07 14:28:10.741779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f0260a1cdf'
down_revision = '39b38487f235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('venues', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artists', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
