"""empty message

Revision ID: 39b38487f235
Revises: 8a4695349329
Create Date: 2022-08-07 14:22:56.224978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b38487f235'
down_revision = '8a4695349329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'seeking_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('venues', 'genres')
    op.alter_column('artists', 'seeking_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
